#!/bin/sh

# script to package generated _site file from hakyll project in /site to aws via codedeploy
# ASSUMES _site has been copied into aws-code-deploy and that resulting dir, published as
# an artifact, is first argument to script

set -e
# Any subsequent(*) commands which fail will cause the shell script to exit immediately

set -x
# log all cmds

# set up vars

# use first param as target dir
TARGET_DIR=$1

timestamp=`date '+%Y_%m_%d__%H_%M_%S'`
S3Bucket="imminent-axolotl"
S3Key="revisions/imminent-axolotl-app-$timestamp.zip"
S3Loc="s3://$S3Bucket/$S3Key"


# bundle up zip and publish as revision

aws deploy push \
  --application-name imminent-axolotl \
  --description "This is a revision for the application imminent-axolotl created at $timestamp" \
  --ignore-hidden-files \
  --s3-location $S3Loc \
  --source aws-code-deploy


# create deployment from revision
# TODO: better description?
aws deploy create-deployment --application-name imminent-axolotl --s3-location bucket=$S3Bucket,key=$S3Key,bundleType=zip --deployment-group-name imminent-axolotl-fleet --description "lorem ipsum"
