#!/bin/sh

# script to package generated _site file from hakyll project in /site to aws via codedeploy
# convenience tool for local use only, actual deploy is inlined in .circleci/config.yml


set -e
# Any subsequent(*) commands which fail will cause the shell script to exit immediately

set -x
# log all cmds

# set up vars

timestamp=`date '+%Y_%m_%d__%H_%M_%S'`
S3Bucket="imminent-axolotl"
S3Key="revisions/imminent-axolotl-app-$timestamp.zip"
S3Loc="s3://$S3Bucket/$S3Key"



# first draft, fragile af wrt build artifact presence

# delete old _site file, if any
if [ -d aws-code-deploy/_site ]; then
  rm -r aws-code-deploy/_site
fi

mkdir aws-code-deploy/_site

cd lamassu-lifeboat
stack install --local-bin-path ../aws-code-deploy/_site --copy-bins
cp -r config ../aws-code-deploy/_site
cp -r static ../aws-code-deploy/_site
cd ..

cd site
stack build
stack exec site build
cp -r _site ../aws-code-deploy/_site/static/test
cd ..

# bundle up zip and publish as revision

aws deploy push \
  --application-name imminent-axolotl-tf \
  --description "This is a revision for the application imminent-axolotl created at $timestamp" \
  --ignore-hidden-files \
  --s3-location $S3Loc \
  --source aws-code-deploy


# create deployment from revision

aws deploy create-deployment --application-name imminent-axolotl-tf --s3-location bucket=$S3Bucket,key=$S3Key,bundleType=zip --deployment-group-name imminent-axolotl-tf --description "lorem ipsum v2 bb"
