version: 2
jobs:
  build-job:
    docker:
      - image: pkinsky/circleci:imminent-axolotl
    steps:
      - checkout
      - run:
          name: Build project, use project to build site artifacts
          command: |
            pushd site
            stack build
            stack exec site build
            popd
            cp -r site/_site aws-code-deploy

      #store revision in cache for use by deploy step of same workflow
      - save_cache:
          key: revision-{{ .Branch }}-{{ .Revision }}
          paths:
            - "aws-code-deploy"


  deploy-job:
    docker:
      - image: pkinsky/circleci:imminent-axolotl
    steps:
      - run:
          name: get AWS cli tools
          command: |
            apt-get update
            apt-get install -y curl unzip python
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws


      # grab cached static site (build artifacts)
      - restore_cache:
          keys:
            - revision-{{ .Branch }}-{{ .Revision }}

      - run:
          name: run AWS deploy script
          command: |
            pwd
            ls -al
            ./aws-deploy-script aws-code-deploy



version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          # commented out for testing
          # filters:
          #   branches:
          #     only: master
