version: 2
jobs:
  build:
    docker:
      - image: pkinsky/circleci:imminent-axolotl
    steps:
      - checkout
      - run:
          name: Build project, use project to build site artifacts
          command: |
            pushd site
            stack build
            stack exec site build
            popd
      - run:
          name: Print the Current Time
          command: date
