version: 2
jobs:
  build:
    docker:
      - image: pkinsky/circleci:imminent-axolotl
    steps:
      - checkout
      - run:
          name: Build project
          #todo: feels hacky needing to set LANG like this here
          command: |
            pushd site
            file -i about.rst
            cat about.rst
            LANG=en_US.UTF-8 stack build
            LANG=en_US.UTF-8 stack exec site build
            popd
      - run:
          name: Print the Current Time
          command: date
